import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex flex-col min-h-screen items-center justify-between p-4 md:p-32 bg-rose-300">
          <div className="w-full bg-blue-100 p-10 h-full rounded-md shadow-lg space-y-5">
            <div className="text-center p-5">
              <Link href={"/"} className="text-4xl font-bold text-rose-500">
                Expense Tracker
              </Link>
            </div>
            <Toaster />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
